<template>
  <div class="container mx-auto my-16 xl:text-lg terms">
    <p class="text-xl font-bold uppercase mb-5">Terms & Conditions</p>
    <p class="font-medium uppercase mb-3">General Terms</p>
    <p class="uppercase mb-5">
      PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THE SITE.
      BY ACCESSING AND CONTINUING TO USE THE SITE OR THE SERVICES THEREOF,
      YOU WILL BE DEEMED TO HAVE ACCEPTED THESE TERMS AND CONDITIONS AND TO
      BE BOUND BY THE TERMS OF SERVICE CONTAINED IN THE TERMS & CONDITIONS
      OUTLINED BELOW. THESE TERMS APPLY TO THE ENTIRE WEBSITE AND ANY EMAIL
      OR OTHER TYPE OF COMMUNICATION BETWEEN YOU AND BAAN THAI MALAYSIA.
    </p>
    <p class="mb-5">
      This Website allows you to access the services of Baan Thai Malaysia
      such as reservation and placing of orders. The Website also provides
      marketing and promotional information about our products, services
      and activities on offer by Baan Thai Malaysia. These Terms & Conditions
      are a contract between you and Baan Thai Malaysia (referred to in
      these Terms & Conditions as "Baan Thai Malaysia", "us", "we" or "our"),
      the provider of the Baan Thai Malaysia website and the services
      accessible from the Baan Thai Malaysia website.
    </p>
    <p class="mb-10">
      These Terms & Conditions are a contract between you and Baan Thai Malaysia
      (referred to in these Terms & Conditions as "Baan Thai Malaysia", "us",
      "we" or "our"), the provider of the Baan Thai Malaysia website and the
      services accessible from the Baan Thai Malaysia website.
    </p>

    <p class="font-medium mb-3">Definitions:</p>
    <p class="font-medium mb-3">For this Terms & Conditions:</p>
    <ul style="list-style-type:disc;" class="mb-8">
      <li>
        Cookie: small amount of data generated by a website and saved by your
        web browser. It is used to identify your browser, provide analytics,
        remember information about you such as your language preference or
        login information.
      </li>
      <li>
        Company: when this policy mentions “Company,” “we,” “us,” or “our,” it
        refers to Baan Thai Malaysia, (Address: Lot pt 15288a, Jalan Kuchai
        Lama, 58200 Kuala Lumpur, Federal Territory of Kuala Lumpur) that is
        responsible for your information under this Terms & Conditions.
      </li>
      <li>
        Country: where Baan Thai Malaysia or the owners/founders of Baan
        Thai Malaysia are based, in this case is Malaysia.
      </li>
      <li>
        Device: any internet connected device such as a phone, tablet, computer 
        or any other device that can be used to visit Baan Thai Malaysia and use
        the services.
      </li>
      <li>
        Service: refers to the service provided by Baan Thai Malaysia as
        described in the relative terms (if available) and on this platform.
      </li>
      <li>
        Third-party service: refers to advertisers, contest sponsors,
        promotional and marketing partners, and others who provide our
        content or whose products or services we think may interest you.
      </li>
      <li>
        Website: Baan Thai Malaysia’s site, which can be accessed via this
        URL: https://baanthaimalaysia.com/
      </li>
      <li>
        Purchasing: refers to online transaction that incurred monetary. 
      </li>
    </ul>

    <p class="font-medium mb-5">Use of the Website:</p>
    <p class="mb-3">
      The Website and its content are made available for your personal, non-commercial
      use. The Website should not be used for unlawful, immoral or illegal purposes or
      for any purpose other than those stated in the Terms and Conditions. We reserve
      the right to deny access to the Website to any user who violates the Terms and
      Conditions or at our sole discretion. The services of the Sites are available
      only to individuals who can form legally binding contracts under applicable
      law, and thus, are not available to minors. By using the Sites, you represent
      that you are of sufficient legal age to use the Sites and to create binding
      legal obligations for any liability you may incur as a result of the use of
      the Sites.
    </p>
    <p class="mb-8">
      The Website contains proprietary information, content and materials, including but
      not limited to text, graphics, images, photographs, videos, music, sound, icons,
      logos, designs, trade names, patents, trademarks, software codes and technologies
      ("Content"), that is owned by Baan Thai Malaysia and/or third parties and is
      protected by applicable intellectual property and other laws. No license is
      granted in respect of those intellectual property rights. Your use of the Website
      does not grant, transfer to or confer upon you any right, title or interest in
      the Content.
    </p>
    <p>You agree not to, and you will not permit others to:</p>
    <ul style="list-style-type:disc;" class="mb-8">
      <li>
        Use the Website for any purpose that is unlawful or prohibited by these terms.
      </li>
      <li>
        Modify, make derivative works of, disassemble, decrypt, reverse compile or
        reverse engineer any part of the website.
      </li>
      <li>
        Remove, alter or obscure any proprietary notice (including any notice of copyright
        or trademark) of Baan Thai Malaysia or its affiliates, partners, suppliers or the
        licensors of the website.
      </li>
      <li>
        Use the website to post contributions that are unlawful, obscene, vulgar,
        defamatory, abusive, damaging, disruptive, inappropriate, offensive, inaccurate,
        pornographic, vulgar, indecent, profane, hateful, racially or ethnically offensive,
        obscene, lewd, lascivious, filthy, threatening, excessively violent, harassing or
        otherwise objectionable.
      </li>
      <li>
        Use or exploit the Site or post Contributions for any commercial purpose, including
        but not limited to posting Contributions that contain advertisements, publicity or
        solicitation for products or services (other than Baan Thai Malaysia’s products and
        services).
      </li>
    </ul>
    
    <p class="font-medium mb-5">Sending Orders and Reservation</p>
    <p>Prices</p>
    <p class="mb-8">
      All prices are exclusives of service charge and applicable tax. We reserve the rights
      to change prices at any time without notice. In certain cases, promotional prices apply.
      These prices are valid only during a specific period as long as stocks last. No
      entitlement to these prices may be invoked before or after the specific period.
    </p>
    <p>Reservation</p>
    <p class="mb-5">
      By using this Website to make reservations with a us, you agree to be bound by all of
      such standard terms and conditions and by any other policies, terms and conditions
      that may apply. By using this Website to make reservations, you hereby authorize us
      to use your personal information including your name, telephone number, or any credit/
      debit card information that you provide to us for the purpose of the reservation.
    </p>
    <p class="mb-2">
      We respectfully ask that you are ready to be seated at the time of your reservation to
      ensure the best possible level of service to all of our customers. Your table will be
      held for 15 minutes after which time it may be allocated to another customer.
    </p>
    <p class="mb-5">
      Tables are available for two hours or such shorter time communicated to you in your
      booking confirmation, after which they will be re-booked for another customer. Please
      do let us know if you would like to stay at your table for longer than two hours and,
      if we have space available, we will do our best to accommodate you. 
    </p>

    <p>Dine-In</p>
    <p>We reserves the right to require proper proof of identity from during dine-in in the event of:</p>
    <ul style="list-style-type:disc;" class="mb-8">
      <li>Age verification before you are served alcohol or your alcohol is delivered.</li>
      <li>Identity verification when you are participating in birthday promotion.</li>
    </ul>

    <p>Changes and Cancellation by you</p>
    <p class="mb-5">
      The customer is only the person allowed to make amendment(s) and cancellation of the reservation.
      All cancellations must be made by contacting our reservation office.
    </p>

    <p>Changes and Cancellation by us:</p>
    <p class="mb-5">
      We reserve the right to correct errors on both before and after bookings have been confirmed
      and cancel confirmed bookings. If we have to make a significant change or cancel, we will
      inform you as soon as possible. Cancelling or accepting the cancellation in which case you
      will receive a full refund of all monies you have paid to us, if any.
    </p>

    <p>Seating Requests:</p>
    <p class="mb-5">All seating requests will be taken into consideration but are not guaranteed.</p>

    <p>Food Safety and Allergens</p>
    <p class="mb-5">
      We respectfully ask that food that has not been prepared in our kitchens is not to be consumed
      on our premises. We are unable to guarantee that our menu items are free from allergens or
      cross-contamination. Please let us know of any allergies before you place your order at the
      restaurant. 
    </p>

    <p class="mb-5">Your Suggestions</p>
    <p class="mb-5">
      Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions")
      provided by you to Baan Thai Malaysia with respect to the website shall remain the sole
      and exclusive property of Baan Thai Malaysia.
    </p>
    <p class="mb-8">
      Baan Thai Malaysia shall be free to use, copy, modify, publish, or redistribute the
      Suggestions for any purpose and in any way without any credit or any compensation
      to you. You irrevocably assign to us all right, title and interest in and to the
      Suggestions and agree to provide us with any assistance we may require to document,
      amend and maintain our rights in the Suggestions.
    </p>
    
    <p class="mb-3">Your Consent</p>
    <p class="mb-7">
      We've updated our “Terms & Conditions” to provide you with complete transparency into
      what is being set when you visit our site and how it's being used. By using our
      website, registering an account, or making a purchase, you hereby consent to our
      Terms & Conditions.
    </p>

    <p class="mb-3">Links to Other Websites</p>
    <p class="mb-7">
      This Terms & Conditions applies only to the Services. The Services may contain links
      to other websites not operated or controlled by Baan Thai Malaysia. We are not
      responsible for the content, accuracy or opinions expressed in such websites, and
      such websites are not investigated, monitored or checked for accuracy or completeness
      by us. Please remember that when you use a link to go from the Services to another
      website, our Terms & Conditions are no longer in effect. Your browsing and interactio
       on any other website, including those that have a link on our platform, is subject
       to that website’s own rules and policies. Such third parties may use their own cookies
       or other methods to collect information about you.
    </p>

    <p class="mb-3">Electronic Communications</p>
    <p class="mb-2">
      Baan Thai Malaysia generally communicates with Baan Thai Malaysia Users by electronic means,
      including but not limited to social media community, email, text, WhatsApp and push
      notifications, in accordance with our Privacy Policy.
    </p>
    <p class="mb-8">
      Further, you hereby agree that all notices, disclosures, agreements and other communications
      that we provide to you electronically satisfy any legal requirement that such communications
      be in writing.
    </p>

    <p class="mb-3">Cookies</p>
    <p class="mb-8">
      Baan Thai Malaysia uses "Cookies" to identify the areas of our website that you have visited.
      A Cookie is a small piece of data stored on your computer or mobile device by your web
      browser. We use Cookies to enhance the performance and functionality of our website but
      are non-essential to their use. However, without these cookies, certain functionality like
      you would be required to enter your login details every time you visit the website as we
      would not be able to remember that you had logged in previously. Most web browsers can be
      set to disable the use of Cookies. However, if you disable Cookies, you may not be able to
      access functionality on our website correctly or at all. We never place Personally
      Identifiable Information in Cookies.
    </p>

    <p class="mb-3">Security</p>
    <p class="mb-2">
      To establish a trusted relationship with our customers, we take both privacy of our customers
      and security of customer data seriously.
    </p>
    <p class="mb-8">
      In order to achieve best experience on our website and mobile devices, we are constantly
      developing new and innovative products.  We take reasonable technical and organizational
      precautions against cyber security threats, we work closely with external security experts
      in the industry to find and report the security issues to us in the development and to find
      a solutions to fix the security issues to protect our customer data.
    </p>

    <p class="mb-3">Changes To Our Terms & Conditions</p>
    <p class="mb-8">
      You acknowledge and agree that we may stop (permanently or temporarily) providing the
      Service (or any features within the Service) to you or to users generally at Baan Thai
      Malaysia’s sole discretion, without prior notice to you.
    </p>

    <p class="mb-3">Modifications to Our website</p>
    <p class="mb-8">
      Baan Thai Malaysia reserves the right to modify, suspend or discontinue, temporarily
      or permanently, the website or any service to which it connects, with or without
      notice and without liability to you.
    </p>

    <p class="mb-3">Updates to Our website</p>
    <p class="mb-5">
      Baan Thai Malaysia may from time to time provide enhancements or improvements to the
      features/ functionality of the website, which may include patches, bug fixes, updates,
      upgrades and other modifications ("Updates").
    </p>
    <p class="mb-5">
      Updates may modify or delete certain features and/or functionalities of the website.
      You agree that Baan Thai Malaysia has no obligation to (i) provide any Updates, or
      (ii) continue to provide or enable any particular features and/or functionalities
      of the website to you.
    </p>
    <p class="mb-8">
      You further agree that all Updates will be (i) deemed to constitute an integral part
      of the website, and (ii) subject to the terms and conditions of this Agreement.
    </p>

    <p class="mb-3">Third-Party Services</p>
    <p class="mb-4">We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</p>
    <p class="mb-4">You acknowledge and agree that Baan Thai Malaysia shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Baan Thai Malaysia does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</p>
    <p class="mb-4">Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</p>
    
    <p class="mb-8">Indemnification</p>
    <p class="mb-8">You agree to indemnify and hold Baan Thai Malaysia and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>
    
    <p class="mb-4">No Warranties</p>
    <p class="mb-4">The website is provided to you "AS IS" and "AS AVAaILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Baan Thai Malaysia, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Baan Thai Malaysia provides no warranty or undertaking, and makes no representation of any kind that the website will meet your requirements, achieve any intended results, be compatible or work with any other software, website, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
    <p class="mb-4">Without limiting the foregoing, neither Baan Thai Malaysia nor any Baan Thai Malaysia's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website, or the information, content, and materials or products included thereon; (ii) that the website will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website; or (iv) that the website, its servers, the content, or e-mails sent from or on behalf of Baan Thai Malaysia are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
    <p class="mb-8">Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</p>
    
    <p class="mb-4">Limitation of Liability</p>
    <p class="mb-4">Under no circumstances shall Baan Thai Malaysia team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Baan Thai Malaysia team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.</p>
    <p class="mb-8">To the maximum extent permitted by applicable law, in no event shall Baan Thai Malaysia or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if Baan Thai Malaysia or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
    
    <p class="mb-4">Severability</p>
    <p class="mb-4">If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
    <p class="mb-8">This Agreement, together with the Privacy Policy and any other legal notices published by Baan Thai Malaysia on the Services, shall constitute the entire agreement between you and Baan Thai Malaysia concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Baan Thai Malaysia&rsquo;s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. </p>
    
    <p class="mb-4">Waiver</p>
    <p class="mb-4">Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.</p>
    <p class="mb-8">No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.</p>
    
    <p class="mb-4">Amendments to this Agreement</p>
    <p class="mb-4">Baan Thai Malaysia reserves the right, at its sole discretion, to modify or replace this Agreement at any time. </p>
    <p class="mb-8">By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Baan Thai Malaysia.</p>
    
    <p class="mb-4">Entire Agreement</p>
    <p class="mb-4">The Agreement constitutes the entire agreement between you and Baan Thai Malaysia regarding your use of the website and supersedes all prior and contemporaneous written or oral agreements between you and Baan Thai Malaysia.</p>
    <p class="mb-8">You may be subject to additional terms and conditions that apply when you use or purchase other Baan Thai Malaysia's&nbsp;services, which Baan Thai Malaysia will provide to you at the time of such use or purchase.</p>
    
    <p class="mb-4">Promotions</p>
    <p class="mb-4">Baan Thai Malaysia may, from time to time, include contests, promotions, or other activities (&ldquo;Promotions&rdquo;) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.</p>
    <p class="mb-8">Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.</p>
    
    <p class="mb-4">Miscellaneous</p>
    <p class="mb-8">If for any reason a court of competent jurisdiction finds any provision or portion of these Terms &amp; Conditions to be unenforceable, the provision in question will be replaced by a new comparable stipulation admissible by law to be determined by Baan Thai Malaysia and the remainder of these Terms &amp; Conditions will continue in full force and effect. Baan Thai Malaysia operates and controls the Baan Thai Malaysia Service from its offices in Malaysia. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Baan Thai Malaysia Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms &amp; Conditions (which include and incorporate the Baan Thai Malaysia Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and Baan Thai Malaysia concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.</p>
    
    <p class="mb-4">Disclaimer</p>
    <p class="mb-4">Baan Thai Malaysia is not responsible for any content, code or any other imprecision.</p>
    <p class="mb-4">Baan Thai Malaysia does not provide warranties or guarantees.</p>
    <p class="mb-4">In no event shall Baan Thai Malaysia be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. </p>
    <p class="mb-4">Baan Thai Malaysia reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
    <p class="mb-4">The Baan Thai Malaysia Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Baan Thai Malaysia is a distributor and not a publisher of the content supplied by third parties; as such, Baan Thai Malaysia exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Baan Thai Malaysia Service. Without limiting the foregoing, Baan Thai Malaysia specifically disclaims all warranties and representations in any content transmitted on or in connection with the Baan Thai Malaysia Service or on sites that may appear as links on the Baan Thai Malaysia Service, or in the products provided as a part of, or otherwise in connection with, the Baan Thai Malaysia Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Baan Thai Malaysia or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Baan Thai Malaysia does not warrant that the Baan Thai Malaysia Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
    <p class="mb-4">All rights reserved to the RESTAURANT.</p>
    <p class="mb-4">Contact Us</p>
    <p class="mb-4">Don't hesitate to contact us if you have any questions.</p>
    <p class="mb-4">&nbsp;-Via Email: admin@baanthaimalaysia.com</p>
    <p class="mb-4">&nbsp;-Via this Link: https://baanthaimalaysia.com/contact </p>
  </div>
</template>